### ISSUE TITLE
Feature Request - RBAC Access

### ISSUE THREAD

**Issue by eahrend** [bloomberg/goldpinger#11]
Not sure if this is on the roadmap or not, but is there a possibility to use the kubernetes RBAC access to allow access to the metrics server? Ideally I should be able to provide the following:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goldpinger
  namespace: default
-----
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: goldpinger
  namespace: default
rules:
- apiGroups: [""]
  resources:
    - "nodes"
    - "nodes/metrics"
    - "nodes/stats"
    - "nodes/proxy"
    - "pods"
    - "services"
  verbs: ["get", "list"]
-----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: goldpinger
subjects:
- kind: ServiceAccount
  name: goldpinger
  namespace: default
roleRef:
  kind: ClusterRole
  name: goldpinger
  apiGroup: rbac.authorization.k8s.io
-----
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: goldpinger
  name: goldpinger
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: goldpinger
      version: 1.0.0
  template:
    metadata:
      labels:
        app: goldpinger
        version: 1.0.0
    spec:
      containers:
      - env:
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: "80"
        - name: KUBECONFIG
          value: ./kube/config
        - name: REFRESH_INTERVAL
          value: "30"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: <REDACTED>
        imagePullPolicy: IfNotPresent
        name: goldpinger
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: goldpinger
      serviceAccountName: goldpinger
      terminationGracePeriodSeconds: 30
  templateGeneration: 3  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```
Currently providing this will cause the container to crash.

```
018/12/13 17:54:16 Metrics setup - see /metrics
2018/12/13 17:54:16 Kubeconfig specified in  ./kube/config
2018/12/13 17:54:16 Error getting config  stat ./kube/config: no such file or directory
```
