### ISSUE TITLE
Error response from daemon: pull access denied for mynamespace-replaceme/goldpinger, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by gjcarneiro** [bloomberg/goldpinger#13]
In your README "Example YAML", the docker image does not exist.

```
Error response from daemon: pull access denied for mynamespace-replaceme/goldpinger, repository does not exist or may require 'docker login'
```

**Comment by marcosdiez** [comment]
That's because that repository does not exist. Apparently Bloomberg is not publishing the binaries.
You can just compile yourself or use a random one from docker hub, like `image: "gokulpch/goldpinger:1.0.2"` (which I found but have no affiliation whatsoever with the author)

I also had some RBAC permission issues, so this is my whole working YAML file:
The last section should be improved to harden security, but I am still using it in a test cluster.

```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: goldpinger
  labels:
    app: goldpinger
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: goldpinger
  template:
    metadata:
      labels:
        app: goldpinger
    spec:
      containers:
        - name: goldpinger
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "80"
            # # kubeconfig needs to match the location of what's injected in the secret
            # # if not specified goldpinger will default to using in-cluster config
            # - name: KUBECONFIG
            #   value: "./kube/config"
            # refresh interval (seconds) tells goldpinger to call every other instance with that frequency (set to 0 to disable)
            - name: REFRESH_INTERVAL
              value: "30"
            # injecting real hostname will make for easier to understand graphs/metrics
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: "gokulpch/goldpinger:1.0.2"
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: goldpinger
  labels:
    app: goldpinger
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    app: goldpinger
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
```
