### ISSUE TITLE
Question: is the type NodePort service needed to function?

### ISSUE THREAD

**Issue by pandorasNox** [bloomberg/goldpinger#62]
In the [README.md](https://github.com/bloomberg/goldpinger/blob/master/README.md) and the [example-serviceaccounts.yml](https://github.com/bloomberg/goldpinger/blob/master/extras/example-serviceaccounts.yml)

we got

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: goldpinger
  namespace: default
  labels:
    app: goldpinger
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    app: goldpinger
```

which exposes the service to the outside world over the NodePort.

Question is: does goldpinger need it to function or can we just use a normal ClusterIP service?

Security wise it doesn't seems to be a good default to me.
If I wanted, I also just could use `kubectl port-forward` or create a nginx resource for it.
