### ISSUE TITLE
Unable to specify name of instances using HOSTNAME env

### ISSUE THREAD

**Issue by yuripastushenko** [bloomberg/goldpinger#99]
**Describe the bug**
The value of env variable HOSTNAME is not applied to goldpinger instance.

**To Reproduce**
Deploy goldpinger using [yaml example](https://github.com/bloomberg/goldpinger#example-yaml):
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goldpinger-serviceaccount
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: goldpinger
  namespace: default
  labels:
    app: goldpinger
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: goldpinger
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
      labels:
        app: goldpinger
    spec:
      serviceAccount: goldpinger-serviceaccount
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: goldpinger
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
            # injecting real hostname will make for easier to understand graphs/metrics
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # podIP is used to select a randomized subset of nodes to ping.
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: "docker.io/bloomberg/goldpinger:v3.0.0"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            limits:
              memory: 80Mi
            requests:
              cpu: 1m
              memory: 40Mi
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: goldpinger
  namespace: default
  labels:
    app: goldpinger
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      name: http
  selector:
    app: goldpinger
```

**Expected behavior**
In UI, goldpinger instances have name of the nodes where they are placed.

**Actual behavior**
In UI, goldpinger instances have name of the pods where they are placed.

**Screenshots**
<img width="1192" alt="Снимок экрана 2021-01-22 в 16 29 01" src="https://user-images.githubusercontent.com/37933672/105496788-006c1100-5ccf-11eb-9e5e-16614bab22d4.png">
<img width="1106" alt="Снимок экрана 2021-01-22 в 16 26 12" src="https://user-images.githubusercontent.com/37933672/105496776-fba75d00-5cce-11eb-9bfb-8bb8c612d8d9.png">

**Environment (please complete the following information):**
 - Kubernetes version v1.17.6

**Comments**
- If I change PORT env - goldpinger applies this change.
- If I start a pod with same yaml, but without readiness probes and change image to ubuntu - the environment variable HOSTNAME is passed in container.
